#!/usr/bin/env bash

if [ -f "/sys/class/power_supply/BAT0/status" ]; then
    battery_status=$(cat /sys/class/power_supply/BAT0/status)
    battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)

    echo 'BAT:' $battery_capacity'% ('$battery_status')'
fi
