#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s $DOTFILES/nvim $HOME/.config/nvim

ln -sf $DOTFILES/vimrc $HOME/.vimrc

ln -s $DOTFILES/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/stubs
ln -s $DOTFILES/stubs $HOME/stubs

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
ln -sf $DOTFILES/zsh/zsh_aliases $HOME/.zsh_aliases
ln -sf $DOTFILES/zsh/zsh_functions $HOME/.zsh_functions

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
