#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf $HOME/.config/sublime-text/Packages/User
ln -s $DOTFILES/User $HOME/.config/sublime-text/Packages/User

ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/stubs
ln -s $DOTFILES/stubs $HOME/stubs

ln -sf $DOTFILES/xbindkey/xbindkeysrc $HOME/.xbindkeysrc

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc
ln -sf $DOTFILES/zsh/zsh_aliases $HOME/.zsh_aliases

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
