# theme = 'gruvbox'
# theme = 'gruvbox_light'
# theme = 'papercolor-light'
# theme = 'papercolor-dark'
# theme = 'darcula'
# theme = 'solarized_light'
# ayu_mirage dark_plus edge_default everforest_dark_hard grbx_mix_light_hard grbx_original_light_medium
theme = 'gruvbox_mix_light_medium'

[editor]
# line-number = 'relative'
mouse = false
bufferline = 'multiple'
gutters = ["diagnostics", "spacer", "diff", "spacer"]

[editor.lsp]
auto-signature-help = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["position", "separator", "position-percentage", "spinner"]
center = []
right = ["diagnostics", "file-name"]
separator = "| "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"A-j" = ["extend_line_above", "delete_selection", "paste_after", "select_mode"]
"A-k" = ["extend_line_above", "delete_selection", "move_line_up", "move_line_up", "paste_after", "select_mode"]
A-n = ["move_prev_long_word_start", "shell_pipe"] 
"x" = ["extend_line_below", "select_mode"]
esc = ["collapse_selection", "keep_primary_selection"]
";" = "command_mode"
C-w = ":wq"
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"A-f" = [":new", ":insert-output lfpick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme gruvbox_mix_light_soft"]

[keys.normal."space"]
"c" = ["toggle_comments"]
"q" = [":buffer-close"]
"w" = { "w" = [":w"]}

[keys.select]
"A-j" = ["delete_selection", "paste_after", "select_mode"]
"A-k" = ["delete_selection", "move_line_up", "move_line_up", "paste_after", "select_mode"]

[keys.select."space"]
"c" = ["toggle_comments"]

[keys.insert]
"A-j" = ["normal_mode", "extend_line_above", "delete_selection", "paste_after", "select_mode"]
"A-k" = ["normal_mode", "extend_line_above", "delete_selection", "move_line_up", "move_line_up", "paste_after", "select_mode"]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
';' = { ';' = ["normal_mode", ":insert-output echo -n ';'", "move_char_right"] } # Maps `jk` to exit insert mode
A-o = ["open_below"]
A-n = ["normal_mode", "move_prev_long_word_start", "shell_pipe"] 
