gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
  allBranchesLogCmd: 'git log --all --graph --pretty=format:"%s %C(auto)%d%Creset" --date=short --date-order'
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
os:
  editCommand: "hx"
