-- autocmd FileType php autocmd BufEnter  <buffer> call FoldUseStatements()
-- 
-- function FoldUseStatements()
--   let lines = []
-- 
--   let lines = filter(range(1, line('$')), 'match(getline(v:val), "^use.*;$") != -1')
-- 
--   if len(lines) == 0
--       return
--   endif
-- 
--   " echo lines[0] . ',' . lines[-1] . "fold"
--   execute lines[0] . ',' . lines[-1] . "fold"
-- endfunction

