export ZSH=$HOME/.oh-my-zsh
export EDITOR=gnome-terminal

ZSH_THEME="robbyrussell"
HIST_STAMPS="yyyy-mm-dd"

plugins=()

source $ZSH/oh-my-zsh.sh
source ~/.zsh_functions
source ~/.zsh_aliases

path=(
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    $HOME/go/bin
    $HOME/.cargo/bin
    ./vendor/bin
    $HOME/dotfiles/scripts
    $path
)

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

bindkey -v

bindkey '^P' history-beginning-search-backward
bindkey '^N' history-beginning-search-forward
