export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"
HIST_STAMPS="yyyy-mm-dd"

plugins=(
    history-substring-search
)

source $ZSH/oh-my-zsh.sh
source ~/.zsh_functions
source ~/.zsh_aliases

path=(
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    $HOME/go/bin
    $HOME/.cargo/bin
    ./vendor/bin
    $HOME/dotfiles/scripts
    $path
)

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

bindkey -v

bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi

if [ -z "$XDG_CURRENT_DESKTOP" ]; then
    export XDG_CURRENT_DESKTOP=sway
fi
if [ -z "$XDG_CONFIG_HOME" ]; then
    export XDG_CONFIG_HOME=$HOME/.config
fi
if [ -z "$WAYLAND_DISPLAY" ]; then
    export WAYLAND_DISPLAY=wayland-0
fi
