#!/usr/bin/env bash

if [ -f "/sys/class/power_supply/BAT0/status" ]; then
    battery_status=$(cat /sys/class/power_supply/BAT0/status)
    battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    consumption=$(awk '{print $1*10^-6 "W"}' /sys/class/power_supply/BAT0/power_now)

    echo 'BAT:' $battery_capacity'% ('$battery_status') - '$consumption
fi
