#!/usr/bin/env bash

BRIGHTNESS=$(echo $(cat /sys/class/backlight/intel_backlight/actual_brightness)"*100/"$(cat /sys/class/backlight/intel_backlight/max_brightness) | bc)

if [ $BRIGHTNESS ]; then
    echo 'BRI:' $BRIGHTNESS'%'
fi
